# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make

    - name: Go lang Format Check
      run: |
        if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then
          exit 1
        fi

    - name: Python tooling Format Check
      run: |
        pip install flake8
        if [ "$(flake8 orchestrator/ | wc -l)" -gt 0 ]; then
          exit 1
        fi

    - name: Test
      run: go test -v ./...
